var quotes = [
    {"quote":"It is difficult to say what is impossible, for the dream of yesterday is the hope of today and the reality of tomorrow.","author":"Robert H. Goddard"},
    {"quote":"No matter what people tell you, words and ideas can change the world.","author":"Robin Williams"},
    {"quote":"Worry never robs tomorrow of its sorrow, it only saps today of its joy.","author":"Leo Buscaglia"},
    {"quote":"We have all the light we need, we just need to put it in practice.","author":"Albert Pike"},
    {"quote":"If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced.","author":"Vincent Van Gogh"},
    {"quote":"Miracles are not contrary to nature, but only contrary to what we know about nature.","author":"Saint Augustine"},
    {"quote":"I learn something every time I go into the mountains.","author":"Michael Kennedy"},
    {"quote":"The man who is swimming against the stream knows the strength of it.","author":"Woodrow Wilson"},
    {"quote":"Success is the sum of small efforts - repeated day in and day out.","author":"Robert Collier"},
    {"quote":"Most people have the will to win, few have the will to prepare to win.","author":"Bobby Knight"},
    {"quote":"To suppose that any form of government will secure liberty or happiness without any virtue in the people, is a chimerical idea.","author":"James Madison"},
    {"quote":"Knowledge will forever govern ignorance; and a people who mean to be their own governors must arm themselves with the power which knowledge gives.","author":"James Madison"},
    {"quote":"My religion is very simple. My religion is kindness.","author":"Dalai Lama"},
    {"quote":"A so-called happy marriage corresponds to love as a correct poem to an improvised song.","author":"Karl Wilhelm Friedrich Schlegel"},
    {"quote":"We waste time looking for the perfect lover, instead of creating the perfect love.","author":"Tom Robbins"},
    {"quote":"Hatred does not cease by hatred, but only by love; this is the eternal rule.","author":"Buddha"},
    {"quote":"If you can't describe what you are doing as a process, you don't know what you're doing.","author":"W. Edwards Deming"},
    {"quote":"Treasure your relationships, not your possessions.","author":"Anthony J. D'Angelo"},
    {"quote":"There is little more powerful than when truth joins action.","author":"Bryant H. McGill"},
    {"quote":"Freedom is not a gift nor does it simply exist for us to have, but rather it is a sacred duty, and its blessed yield of hope is born from none other than the blood of the innocent.","author":"Bryant H. McGill"},
    {"quote":"Don't make the mistake of thinking that you have to agree with people and their beliefs to defend them from injustice.","author":"Bryant H. McGill"},
    {"quote":"True freedom is where an individual's thoughts and actions are in alignment with that which is true, correct, and of honor - no matter the personal price.","author":"Bryant H. McGill"},
    {"quote":"It is better to lose everything you have to keep the balance of justice level, than to live a life of petty privilege devoid of true freedom.","author":"Bryant H. McGill"},
    {"quote":"Do not let your ambitions become a sanctuary for your failures.","author":"Bryant H. McGill"},
    {"quote":"Unfortunately, your reputation often rests not on your ability to do what you say, but rather on your ability to do what people expect.","author":"Bryant H. McGill"},
    {"quote":"The conflicts we have with the outside world are often conflicts we have within ourselves.","author":"Bryant H. McGill"},
    {"quote":"The best way to win against the intolerable is to tolerate them, for this they have seldom dealt with. Your indulgence may soften their malice and open their eyes to more honorable ways.","author":"Bryant H. McGill"},
    {"quote":"The supreme lesson of any education should be to think for yourself and to be yourself; absent this attainment, education creates dangerous, stupefying conformity.","author":"Bryant H. McGill"},
    {"quote":"No time is better spent than that spent in the service of your fellow man.","author":"Bryant H. McGill"},
    {"quote":"Change will never happen when people lack the ability and courage to see themselves for who they are.","author":"Bryant H. McGill"},
    {"quote":"One of the most sincere forms of respect is actually listening to what another has to say.","author":"Bryant H. McGill"},
    {"quote":"There is no love without forgiveness, and there is no forgiveness without love.","author":"Bryant H. McGill"},
    {"quote":"Everything that irritates us about others can lead us to an understanding of ourselves.","author":"Carl Jung"},
    {"quote":"True love is quiescent, except in the nascent moments of true humility.","author":"Bryant H. McGill"},
    {"quote":"Electric communication will never be a substitute for the face of someone who with their soul encourages another person to be brave and true.","author":"Charles Dickens"},
    {"quote":"What sculpture is to a block of marble, education is to the soul.","author":"Joseph Addison"},
    {"quote":"To be angry is to revenge the faults of others on ourselves.","author":"Alexander Pope"},
    {"quote":"Every reform, however necessary, will by weak minds be carried to an excess, that itself will need reforming.","author":"Samuel Taylor Coleridge"},
    {"quote":"In politics, what begins in fear usually ends in failure.","author":"Samuel Taylor Coleridge"},
    {"quote":"Our own heart, and not other men's opinions form our true honor.","author":"Samuel Taylor Coleridge"},
    {"quote":"Happiness is that state of consciousness which proceeds from the achievement of one's values.","author":"Ayn Rand"},
    {"quote":"Kites rise highest against the wind - not with it.","author":"Winston Churchill"},
    {"quote":"Advice is like snow - the softer it falls, the longer it dwells upon, and the deeper it sinks into the mind.","author":"Samuel Taylor Coleridge"},
    {"quote":"Waste no more time arguing about what a good man should be. Be one.","author":"Marcus Aurelius"},
    {"quote":"Faith is taking the first step even when you don't see the whole staircase.","author":"Martin Luther King, Jr."},
    {"quote":"I should like to be able to love my country and still love justice.","author":"Albert Camus"},
    {"quote":"A free press can, of course, be good or bad, but, most certainly without freedom, the press will never be anything but bad.","author":"Albert Camus"},
    {"quote":"I know of only one duty, and that is to love.","author":"Albert Camus"},
    {"quote":"Real generosity toward the future lies in giving all to the present.","author":"Albert Camus"},
    {"quote":"Don't walk behind me;<br/> I may not lead.<br/> Don't walk in front of me;<br/> I may not follow.<br/> Just walk beside me and be my friend.","author":"Unknown"},
    {"quote":"But what is happiness except the simple harmony between a man and the life he leads?","author":"Albert Camus"},
    {"quote":"We would accomplish many more things if we did not think of them as impossible.","author":"Vince Lombardi"},
    {"quote":"A thousand words will not leave so deep an impression as one deed.","author":"Henrik Ibsen"},
    {"quote":"Looking back, I have this to regret, that too often when I loved, I did not say so.","author":"Ray Stannard Baker"},
    {"quote":"A certain amount of opposition is a great help to a man. Kites rise against, not with, the wind.","author":"Lewis Mumford"},
    {"quote":"Failure is success if we learn from it.","author":"Malcolm Forbes"},
    {"quote":"At the center of non-violence stands the principle of love.","author":"Martin Luther King, Jr."},
    {"quote":"Life's most persistent and urgent question is, 'What are you doing for others?'","author":"Martin Luther King, Jr."},
    {"quote":"The price of greatness is responsibility.","author":"Winston Churchill"},
    {"quote":"I love to think of nature as an unlimited broadcasting station, through which God speaks to us every hour, if we will only tune in.","author":"George Washington Carver"},
    {"quote":"Fear of something is at the root of hate for others, and hate within will eventually destroy the hater.","author":"George Washington Carver"},
    {"quote":"Always be a first-rate version of yourself, instead of a second-rate version of somebody else.","author":"Judy Garland"},
    {"quote":"The art of being happy lies in the power of extracting happiness from common things.","author":"Henry Ward Beecher"},
    {"quote":"I think in terms of the day's resolutions, not the years'.","author":"Henry Moore"},
    {"quote":"Kindness in words creates confidence.<br/> Kindness in thinking creates profoundness.<br/> Kindness in giving creates love.","author":"Lao Tzu"},
    {"quote":"Be faithful in small things because it is in them that your strength lies.","author":"Mother Teresa"},
    {"quote":"There's a world of difference between truth and facts. Facts can obscure the truth.","author":"Maya Angelou"},
    {"quote":"The most worth-while thing is to try to put happiness into the lives of others.","author":"Robert Baden-Powell"},
    {"quote":"The progress of rivers to the ocean is not so rapid as that of man to error.","author":"Voltaire"},
    {"quote":"We shall never know all the good that a simple smile can do.","author":"Mother Teresa"},
    {"quote":"Never believe that a few caring people can't change the world. For, indeed, that's all who ever have.","author":"Margaret Mead"},
    {"quote":"Change is the end result of all true learning.","author":"Leo Buscaglia"},
    {"quote":"Wise sayings often fall on barren ground, but a kind word is never thrown away.","author":"Arthur Helps"},
    {"quote":"Love is the difficult realization that something other than oneself is real.","author":"Iris Murdoch"},
    {"quote":"Start with what is right rather than what is acceptable.","author":"Franz Kafka"},
    {"quote":"But surely for everything you have to love you have to pay some price.","author":"Agatha Christie"},
    {"quote":"It is the mark of an educated mind to be able to entertain a thought without accepting it.","author":"Aristotle"},
    {"quote":"To say 'I love you' one must first be able to say the 'I.'","author":"Ayn Rand"},
    {"quote":"The way to get things done is not to mind who gets the credit for doing them.","author":"Benjamin Jowett"},
    {"quote":"Bad officials are the ones elected by good citizens who do not vote.","author":"George Jean Nathan"},
    {"quote":"Learn to say 'no' to the good so you can say 'yes' to the best.","author":"John C. Maxwell"},
    {"quote":"The greatest mistake we make is living in constant fear that we will make one.","author":"John C. Maxwell"},
    {"quote":"In the end, people are persuaded not by what we say, but by what they understand.","author":"John C. Maxwell"},
    {"quote":"Every person has a longing to be significant; to make a contribution; to be a part of something noble and purposeful.","author":"John C. Maxwell"},
    {"quote":"A man must be big enough to admit his mistakes, smart enough to profit from them, and strong enough to correct them.","author":"John C. Maxwell"},
    {"quote":"A leader is one who knows the way, goes the way, and shows the way.","author":"John C. Maxwell"},
    {"quote":"Freedom is nothing but a chance to be better.","author":"Albert Camus"},
    {"quote":"It is not possible to go forward while looking back.","author":"Ludwig Mies van der Rohe"},
    {"quote":"I don't want to be interesting. I want to be good.","author":"Ludwig Mies van der Rohe"},
    {"quote":"Don't let yesterday use up too much of today.","author":"Will Rogers"},
    {"quote":"People's minds are changed through observation and not through argument.","author":"Will Rogers"},
    {"quote":"The breaking of a wave cannot explain the whole sea.","author":"Vladimir Nabokov"},
    {"quote":"The only courage that matters is the kind that gets you from one moment to the next.","author":"Mignon McLaughlin"},
    {"quote":"Love is what you've been through with somebody.","author":"James Thurber"},
    {"quote":"A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.","author":"George Bernard Shaw"},
    {"quote":"Silent gratitude isn't much use to anyone.","author":"Gertrude Stein"},
    {"quote":"We don't see things as they are, we see them as we are.","author":"Anais Nin"},
    {"quote":"Despite everything, I believe that people are really good at heart.","author":"Anne Frank"},
    {"quote":"Only the educated are free.","author":"Epictetus"},
    {"quote":"The wise does at once what the fool does at last.","author":"Baltasar Gracian"},
    {"quote":"The people who influence you are the people who believe in you.","author":"Henry Drummond"},
    {"quote":"Every exit is an entry somewhere else.","author":"Tom Stoppard"},
    {"quote":"The more man meditates upon good thoughts, the better will be his world and the world at large.","author":"Confucius"},
    {"quote":"Opportunity does not knock, it presents itself when you beat down the door.","author":"Kyle Chandler"},
    {"quote":"What you do today can improve all your tomorrows.","author":"Ralph Marston"},
    {"quote":"Perseverance is not a long race; it is many short races one after the other.","author":"Walter Elliot"},
    {"quote":"The secret of getting ahead is getting started.","author":"Mark Twain"},
    {"quote":"If you want to conquer fear, don't sit home and think about it. Go out and get busy.","author":"Dale Carnegie"},
    {"quote":"The past cannot be changed. The future is yet in your power.","author":"Unknown"},
    {"quote":"I never knew how to worship until I knew how to love.","author":"Henry Ward Beecher"},
    {"quote":"Only put off until tomorrow what you are willing to die having left undone.","author":"Pablo Picasso"},
    {"quote":"Computers are useless. They can only give you answers.","author":"Pablo Picasso"},
    {"quote":"I am always doing that which I cannot do, in order that I may learn how to do it.","author":"Pablo Picasso"},
    {"quote":"Youth has no age.","author":"Pablo Picasso"},
    {"quote":"Love and fear. Everything the father of a family says must inspire one or the other.","author":"Joseph Joubert"},
    {"quote":"In art, the hand can never execute anything higher than the heart can imagine.","author":"Ralph Waldo Emerson"},
    {"quote":"Where there is no vision, there is no hope.","author":"George Washington Carver"},
    {"quote":"They're only truly great who are truly good.","author":"George Chapman"},
    {"quote":"True love cannot be found where it does not exist, nor can it be denied where it does.","author":"Torquato Tasso"},
    {"quote":"The only rock I know that stays steady, the only institution I know that works, is the family.","author":"Lee Iacocca"},
    {"quote":"The most wasted of all days is one without laughter.","author":"e. e. cummings"},
    {"quote":"The absence of alternatives clears the mind marvelously.","author":"Henry Kissinger"},
    {"quote":"All our dreams can come true, if we have the courage to pursue them.","author":"Walt Disney"},
    {"quote":"Our doubts are traitors and make us lose the good we oft might win by fearing to attempt.","author":"William Shakespeare"},
    {"quote":"Science is organized knowledge.<br/> Wisdom is organized life.","author":"Immanuel Kant"},
    {"quote":"Talent is God given.<br/> Be humble.<br/> Fame is man-given.<br/> Be grateful.<br/> Conceit is self-given.<br/> Be careful.","author":"John Wooden"},
    {"quote":"To enjoy good health, to bring true happiness to one's family, to bring peace to all, one must first discipline and control one's own mind. If a man can control his mind he can find the way to Enlightenment, and all wisdom and virtue will naturally come to him.","author":"Buddha"},
    {"quote":"For beautiful eyes,<br/> look for the good in others;<br/> for beautiful lips,<br/> speak only words of kindness;<br/> and for poise,<br/> walk with the knowledge that you are never alone.","author":"Audrey Hepburn"},
    {"quote":"To love is to act.","author":"Victor Hugo"},
    {"quote":"The smallest deed is better than the greatest intention.","author":"John Burroughs"},
    {"quote":"You can have no dominion greater or less than that over yourself.","author":"Leonardo da Vinci"},
    {"quote":"The greatest deception men suffer is from their own opinions.","author":"Leonardo da Vinci"},
    {"quote":"People who say it cannot be done should not interrupt those who are doing it.","author":"Unknown"},
    {"quote":"Humility is the solid foundation of all virtues.","author":"Confucius"},
    {"quote":"The strength of a nation derives from the integrity of the home.","author":"Confucius"},
    {"quote":"I hear and I forget.<br/> I see and I remember.<br/> I do and I understand.","author":"Confucius"},
    {"quote":"We must learn to live together as brothers or perish together as fools.","author":"Martin Luther King, Jr."},
    {"quote":"Injustice anywhere is a threat to justice everywhere.","author":"Martin Luther King, Jr."},
    {"quote":"The time is always right to do what is right.","author":"Martin Luther King, Jr."},
    {"quote":"In the End, we will remember not the words of our enemies, but the silence of our friends.","author":"Martin Luther King, Jr."},
    {"quote":"Darkness cannot drive out darkness;<br/> only light can do that.<br/> Hate cannot drive out hate;<br/> only love can do that.","author":"Martin Luther King, Jr."},
    {"quote":"Peace comes from within. Do not seek it without.","author":"Buddha"},
    {"quote":"Just as treasures are uncovered from the earth, so virtue appears from good deeds, and wisdom appears from a pure and peaceful mind. To walk safely through the maze of human life, one needs the light of wisdom and the guidance of virtue.","author":"Buddha"},
    {"quote":"What we think, we become.","author":"Buddha"},
    {"quote":"You will not be punished for your anger, you will be punished by your anger.","author":"Buddha"},
    {"quote":"Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.","author":"Buddha"},
    {"quote":"Our Constitution was made only for a moral and religious people. It is wholly inadequate to the government of any other.","author":"John Adams"},
    {"quote":"I must study politics and war that my sons may have liberty to study mathematics and philosophy.","author":"John Adams"},
    {"quote":"The fact that an opinion has been widely held is no evidence whatever that it is not utterly absurd.","author":"Bertrand Russell"},
    {"quote":"If you could say it in words there would be no reason to paint.","author":"Edward Hopper"},
    {"quote":"With the new day comes new strength and new thoughts.","author":"Eleanor Roosevelt"},
    {"quote":"Some people are always grumbling because roses have thorns; I am thankful that thorns have roses.","author":"Alphonse Karr"},
    {"quote":"Too many of us are not living our dreams because we are living our fears.","author":"Les Brown"},
    {"quote":"Life has no limitations, except the ones you make.","author":"Les Brown"},
    {"quote":"The next time you're tempted to groan, you might try to laugh instead.","author":"Joseph B. Wirthlin"},
    {"quote":"What people think and believe and plan are all very important, but what they do is the thing that counts most.","author":"Joseph B. Wirthlin"},
    {"quote":"Sometimes we should express our gratitude for the small and simple things like the scent of the rain, the taste of your favorite food, or the sound of a loved one's voice.","author":"Joseph B. Wirthlin"},
    {"quote":"Rather fail with honor than succeed by fraud.","author":"Sophocles"},
    {"quote":"Nobody made a greater mistake than he who did nothing because he could do only a little.","author":"Edmund Burke"},
    {"quote":"If you are lucky enough to find a way of life you love, you have to find the courage to live it.","author":"John Irving"},
    {"quote":"A successful marriage is an edifice that must be rebuilt every day.","author":"Andre Maurois"},
    {"quote":"One cannot and must not try to erase the past merely because it does not fit the present.","author":"Golda Meir"},
    {"quote":"There is nothing in a caterpillar that tells you it's going to be a butterfly.","author":"R. Buckminster Fuller"},
    {"quote":"It is not in the stars to hold our destiny but in ourselves.","author":"William Shakespeare"},
    {"quote":"Though we travel the world over to find the beautiful, we must carry it with us or we find it not.","author":"Ralph Waldo Emerson"},
    {"quote":"Between saying and doing, many a pair of shoes is worn out.","author":"Iris Murdoch"},
    {"quote":"Success demands singleness of purpose.","author":"Vince Lombardi"},
    {"quote":"Music, I feel, must be emotional first and intellectual second.","author":"Maurice Ravel"},
    {"quote":"So long as the human spirit thrives on this planet, music in some living form will accompany and sustain it and give it expressive meaning.","author":"Aaron Copland"},
    {"quote":"It requires wisdom to understand wisdom: the music is nothing if the audience is deaf.","author":"Walter Lippmann"},
    {"quote":"The man that hath no music in himself, Nor is not moved with concord of sweet sounds, is fit for treasons, stratagems and spoils.","author":"William Shakespeare"},
    {"quote":"Love is a friendship set to music.","author":"Joseph Campbell"},
    {"quote":"Next to the Word of God, the noble art of music is the greatest treasure in the world.","author":"Martin Luther"},
    {"quote":"Music can change the world because it can change people.","author":"Bono"},
    {"quote":"To me there is no picture so beautiful as smiling, bright-eyed, happy children; no music so sweet as their clear and ringing laughter.","author":"P. T. Barnum"},
    {"quote":"Music is love, love is music, music is life, and I love my life. Thank you and good night.","author":"A. J. McLean"},
    {"quote":"Music expresses that which cannot be said and on which it is impossible to be silent.","author":"Victor Hugo"},
    {"quote":"Never apologize for showing feeling. When you do so, you apologize for the truth.","author":"Benjamin Disraeli"},
    {"quote":"It's the friends you can call up at 4 am that matter.","author":"Marlene Dietrich"},
    {"quote":"A great work is made out of a combination of obedience and liberty.","author":"Nadia Boulanger"},
    {"quote":"I'd rather have roses on my table than diamonds on my neck.","author":"Emma Goldman"},
    {"quote":"If you want others to be happy,<br/> practice compassion.<br/> If you want to be happy,<br/> practice compassion.","author":"Dalai Lama"},
    {"quote":"Much that passes as idealism is disguised hatred or disguised love of power.","author":"Bertrand Russell"},
    {"quote":"Simplicity is the ultimate sophistication.","author":"Leonardo Da Vinci"},
    {"quote":"Love is not only something you feel, it is something you do.","author":"David Wilkerson"},
    {"quote":"There are a thousand hacking at the branches of evil to one who is striking at the root.","author":"Henry David Thoreau"},
    {"quote":"If we open a quarrel between past and present, we shall find that we have lost the future.","author":"Winston Churchill"},
    {"quote":"The aim of education is the knowledge, not of facts, but of values.","author":"William Inge"},
    {"quote":"We may pass violets looking for roses. We may pass contentment looking for victory.","author":"Bernard Williams"},
    {"quote":"A single sunbeam is enough to drive away many shadows.","author":"Francis of Assisi"},
    {"quote":"You have succeeded in life when all you really want is only what you really need.","author":"Vernon Howard"},
    {"quote":"Real knowledge is to know the extent of one's ignorance.","author":"Confucius"},
    {"quote":"It is not so much our friends' help that helps us, as the confidence of their help.","author":"Epicurus"},
    {"quote":"We have, I fear, confused power with greatness.","author":"Stewart Udall"},
    {"quote":"Education is a progressive discovery of our own ignorance.","author":"Will Durant"},
    {"quote":"He is happiest, be he king or peasant, who finds peace in his home.","author":"Johann Wolfgang von Goethe"},
    {"quote":"I have never been hurt by what I have not said.","author":"Calvin Coolidge"},
    {"quote":"Love without conversation is impossible.","author":"Mortimer Adler"},
    {"quote":"People only see what they are prepared to see.","author":"Ralph Waldo Emerson"},
    {"quote":"When virtue is lost, benevolence appears, when benevolence is lost right conduct appears, when right conduct is lost, expedience appears. Expediency is the mere shadow of right and truth; it is the beginning of disorder.","author":"Lao Tzu"},
    {"quote":"Governing a great nation is like cooking a small fish - too much handling will spoil it.","author":"Lao Tzu"},
    {"quote":"Those who have knowledge, don't predict. Those who predict, don't have knowledge.","author":"Lao Tzu"},
    {"quote":"When the best leader's work is done the people say, 'We did it ourselves.'","author":"Lao Tzu"},
    {"quote":"If you do not change direction, you may end up where you are heading.","author":"Lao Tzu"},
    {"quote":"The journey of a thousand miles begins with one step.","author":"Lao Tzu"},
    {"quote":"They do not love that do not show their love.","author":"William Shakespeare"},
    {"quote":"To love abundantly is to live abundantly,<br/> and to love forever is to live forever.","author":"Henry Drummond"},
    {"quote":"Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.","author":"Lao Tzu"},
    {"quote":"The return we reap from generous actions is not always evident.","author":"Francesco Guicciardini"},
    {"quote":"Talent does what it can; genius does what it must.","author":"Edward G. Bulwer-Lytton"},
    {"quote":"The best way to cheer yourself up is to try to cheer somebody else up.","author":"Mark Twain"},
    {"quote":"The home is the chief school of human virtues.","author":"William Ellery Channing"},
    {"quote":"Zeal is a volcano, the peak of which the grass of indecisiveness does not grow.","author":"Khalil Gibran"},
    {"quote":"Success is getting what you want. Happiness is wanting what you get.","author":"Dale Carnegie"},
    {"quote":"We aim above the mark to hit the mark.","author":"Ralph Waldo Emerson"},
    {"quote":"A man is what he thinks about all day long.","author":"Ralph Waldo Emerson"},
    {"quote":"Art is not a handicraft, it is the transmission of feeling the artist has experienced.","author":"Leo Tolstoy"},
    {"quote":"My father considered a walk among the mountains as the equivalent of churchgoing.","author":"Aldous Huxley"},
    {"quote":"The hardest arithmetic to master is that which enables us to count our blessings.","author":"Eric Hoffer"},
    {"quote":"I have never in my life learned anything from any man who agreed with me.","author":"Dudley Field Malone"},
    {"quote":"Choose your love, Love your choice.","author":"Thomas S. Monson"},
    {"quote":"Genius ain't anything more than elegant common sense.","author":"Josh Billings"},
    {"quote":"When a woman is talking to you, listen to what she says with her eyes.","author":"Victor Hugo"},
    {"quote":"The love of our private friends is the only preparatory exercise for the love of all men.","author":"John Henry Newman"},
    {"quote":"You must be the change you wish to see in the world.","author":"Mahatma Gandhi"},
    {"quote":"It is not the mountain we conquer but ourselves.","author":"Edmund Hillary"},
    {"quote":"Real happiness is cheap enough, yet how dearly we pay for its counterfeit.","author":"Hosea Ballou"},
    {"quote":"The only sure weapon against bad ideas is better ideas.","author":"Alfred Whitney Griswold"},
    {"quote":"Ten people who speak make more noise than ten thousand who are silent.","author":"Napoleon Bonaparte"},
    {"quote":"Experience is simply the name we give our mistakes.","author":"Oscar Wilde"},
    {"quote":"Every conquering temptation represents a new fund of moral energy. Every trial endured and weathered in the right spirit makes a soul nobler and stronger than it was before.","author":"William Butler Yeats"},
    {"quote":"It is easier to prevent bad habits than to break them.","author":"Benjamin Franklin"},
    {"quote":"To be perfectly happy it does not suffice to possess happiness, it is necessary to have deserved it.","author":"Victor Hugo"},
    {"quote":"To love beauty is to see light.","author":"Victor Hugo"},
    {"quote":"He who opens a school door, closes a prison.","author":"Victor Hugo"},
    {"quote":"Change your opinions, keep to your principles; change your leaves, keep intact your roots.","author":"Victor Hugo"},
    {"quote":"Love takes up where knowledge leaves off.","author":"Thomas Aquinas"},
    {"quote":"The time you enjoy wasting is not wasted time.","author":"Bertrand Russell"},
    {"quote":"The world of reality has its limits; the world of imagination is boundless.","author":"Jean-Jacques Rousseau"},
    {"quote":"The only way to discover the limits of the possible is to go beyond them into the impossible.","author":"Arthur C. Clarke"},
    {"quote":"What we really are matters more than what other people think of us.","author":"Jawaharlal Nehru"},
    {"quote":"If the only prayer you ever say in your entire life is thank you, it will be enough.","author":"Meister Eckhart"},
    {"quote":"We cannot put off living until we are ready.","author":"Jose Ortega y Gasset"},
    {"quote":"Happiness is like a kiss. You must share it to enjoy it.","author":"Bernard Meltzer"},
    {"quote":"Good judgment comes from experience, and experience comes from bad judgment.","author":"Rita Mae Brown"},
    {"quote":"I am grateful for what I am and have. My thanksgiving is perpetual.","author":"Henry David Thoreau"},
    {"quote":"I have learned silence from the talkative, toleration from the intolerant, and kindness from the unkind; yet, strange, I am ungrateful to those teachers.","author":"Khalil Gibran"},
    {"quote":"Your pain is the breaking of the shell that encloses your understanding.","author":"Khalil Gibran"},
    {"quote":"We choose our joys and sorrows long before we experience them.","author":"Khalil Gibran"},
    {"quote":"Out of difficulties grow miracles.","author":"Jean de la Bruyere"},
    {"quote":"Kind words do not cost much. Yet they accomplish much.","author":"Blaise Pascal"},
    {"quote":"Hope is patience with the lamp lit.","author":"Tertullian"},
    {"quote":"To defeat the aggressors is not enough to make peace durable. The main thing is to discard the ideology that generates war.","author":"Ludwig von Mises"},
    {"quote":"Beware the fury of a patient man.","author":"John Dryden"},
    {"quote":"A very small degree of hope is sufficient to cause the birth of love.","author":"Stendhal"},
    {"quote":"Art is not what you see, but what you make others see.","author":"Edgar Degas"},
    {"quote":"The love of liberty is the love of others; the love of power is the love of ourselves.","author":"William Hazlitt"},
    {"quote":"When one must, one can.","author":"Charlotte Whitton"},
    {"quote":"I have no methods; all I do is accept people as they are.","author":"Joan Rivers"},
    {"quote":"What we observe is not nature itself, but nature exposed to our method of questioning.","author":"Werner Heisenberg"},
    {"quote":"If the stars should appear but one night every thousand years how man would marvel and stare.","author":"Ralph Waldo Emerson"},
    {"quote":"Better keep yourself clean and bright; you are the window through which you must see the world.","author":"George Bernard Shaw"},
    {"quote":"Not what we have But what we enjoy, constitutes our abundance.","author":"Epicurus"},
    {"quote":"The misfortune of the wise is better than the prosperity of the fool.","author":"Epicurus"},
    {"quote":"To love another person is to see the face of God.","author":"Victor Hugo"},
    {"quote":"Life consists not in holding good cards but in playing those you hold well.","author":"Josh Billings"},
    {"quote":"Democracy and socialism have nothing in common but one word, equality. But notice the difference: while democracy seeks equality in liberty, socialism seeks equality in restraint and servitude.","author":"Alexis de Tocqueville"},
    {"quote":"We first make our habits, and then our habits make us.","author":"John Dryden"},
    {"quote":"There are many men of principle in both parties in America, but there is no party of principle.","author":"Alexis de Tocqueville"},
    {"quote":"The real problem is not whether machines think but whether men do.","author":"B. F. Skinner"},
    {"quote":"Education is the movement from darkness to light.","author":"Allan Bloom"},
    {"quote":"Many a trip continues long after movement in time and space have ceased.","author":"John Steinbeck"},
    {"quote":"Courage is fear holding on a minute longer.","author":"George S. Patton"},
    {"quote":"Have patience. All things are difficult before they become easy.","author":"Saadi"},
    {"quote":"He who angers you conquers you.","author":"Elizabeth Kenny"},
    {"quote":"If your knees aren't green by the end of the day, you ought to seriously re-examine your life.","author":"Bill Watterson"},
    {"quote":"The supernatural is the natural not yet understood.","author":"Elbert Hubbard"},
    {"quote":"Change your life today. Don't gamble on the future, act now, without delay.","author":"Simone de Beauvoir"},
    {"quote":"We must not allow other people's limited perceptions to define us.","author":"Virginia Satir"},
    {"quote":"Don't cry because it's over. Smile because it happened.","author":"Dr. Seuss"},
    {"quote":"You can't become who you want to be without leaving where you are.","author":"Unknown"},
    {"quote":"He is a wise man that does not grieve for those things that he has not, but rejoices for those things which he has.","author":"Unknown"},
    {"quote":"Character may be manifested in the great moments, but it is made in the small ones.","author":"Phillips Brooks"},
    {"quote":"Better remain silent, better not even think, if you are not prepared to act.","author":"Annie Besant"},
    {"quote":"Either I will find a way, or I will make one.","author":"Philip Sidney"},
    {"quote":"Don't pray when it rains if you don't pray when the sun shines.","author":"Satchel Paige"},
    {"quote":"Hope is like the sun, which, as we journey toward it, casts the shadow of our burden behind us.","author":"Samuel Smiles"},
    {"quote":"We cannot live only for ourselves. A thousand fibers connect us with our fellow men.","author":"Herman Melville"},
    {"quote":"Love and compassion are necessities, not luxuries. Without them humanity cannot survive.","author":"Dalai Lama"},
    {"quote":"If you want to build a ship, don't drum up people to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.","author":"Antoine de Saint-Exupery"},
    {"quote":"For every minute you remain angry, you give up sixty seconds of peace of mind.","author":"Ralph Waldo Emerson"},
    {"quote":"What lies behind you and what lies in front of you, pales in comparison to what lies inside of you.","author":"Ralph Waldo Emerson"},
    {"quote":"The future is no more uncertain than the present.","author":"Walt Whitman"},
    {"quote":"Let every nation know, whether it wishes us well or ill, that we shall pay any price, bear any burden, meet any hardship, support any friend, oppose any foe to assure the survival and the success of liberty.","author":"John F. Kennedy"},
    {"quote":"There are risks and costs to action. But they are far less than the long range risks of comfortable inaction.","author":"John F. Kennedy"},
    {"quote":"Sir, my concern is not whether God is on our side; my greatest concern is to be on God's side, for God is always right.","author":"Abraham Lincoln"},
    {"quote":"I hope I shall possess firmness and virtue enough to maintain what I consider the most enviable of all titles, the character of an honest man.","author":"George Washington"},
    {"quote":"Don't judge each day by the harvest you reap but by the seeds that you plant.","author":"Robert Louis Stevenson"},
    {"quote":"No act of kindness, no matter how small, is ever wasted.","author":"Aesop"},
    {"quote":"Pursue what is Meaningful, not what is Expedient.","author":"Jordan Peterson"},
    {"quote":"The question isn't who is going to let me; it's who is going to stop me.","author":"Ayn Rand"},
    {"quote":"I believe things cannot make themselves impossible.","author":"Stephen Hawking"},
    {"quote":"When I was young, I admired clever people. Now that I am old, I admire kind people.","author":"Abraham Joshua Heschel"},
    {"quote":"Wonder rather than doubt is the root of all knowledge.","author":"Abraham Joshua Heschel"},
    {"quote":"God is of no importance unless He is of supreme importance.","author":"Abraham Joshua Heschel"},
    {"quote":"A happy life consists not in the absence, but in the mastery of hardships.","author":"Helen Keller"},
    {"quote":"If we had no faults we should not take so much pleasure in noting those of others.","author":"François de La Rochefoucauld"},
    {"quote":"What makes the vanity of others insufferable to us is that it wounds our own.","author":"François de La Rochefoucauld"},
    {"quote":"Quarrels would not last long if the fault were only on one side.","author":"François de La Rochefoucauld"},
    {"quote":"A people that values its privileges above its principles soon loses both.","author":"Dwight D. Eisenhower"},
    {"quote":"I disapprove of what you say, but I will defend to the death your right to say it.","author":"Evelyn Beatrice Hall"},
    {"quote":"I hear you say 'Why?' Always 'Why?' You see things; and you say 'Why?' But I dream things that never were; and I say 'Why not?'","author":"George Bernard Shaw"},
    {"quote":"It is better to be hated for what you are than loved for what you are not.","author":"André Gide"},
    {"quote":"Faith is not certainty. Faith is the courage to live with uncertainty.","author":"Rabbi Jonathan Sacks"},
    {"quote":"Seek First to Understand, Then to be Understood.","author":"Steven R. Covey"},
    {"quote":"The Sundial:<br/>The shadow by my finger cast<br/>Divides the future from the past:<br/>Before it, sleeps the unborn hour<br/>In darkness, and beyond thy power:<br/>Behind its unreturning line,<br/>The vanished hour, no longer thine:<br/>One hour alone is in thy hands,--<br/>The NOW on which the shadow stands.","author":"Henry Van Dyke"},
    {"quote":"We gain the strength of the temptation we resist.","author":"Ralph Waldo Emerson"},
    {"quote":"You cannot do a kindness too soon, for you never know how soon it will be too late.","author":"Ralph Waldo Emerson"},
    {"quote":"Fiction reveals truth that reality obscures.","author":"Ralph Waldo Emerson"},
    {"quote":"Truth is the property of no individual but is the treasure of all [people].","author":"Ralph Waldo Emerson"},
    {"quote":"Before we acquire great power we must acquire wisdom to use it well.","author":"Ralph Waldo Emerson"},
    {"quote":"A hero is no braver than an ordinary man, but he is brave five minutes longer.","author":"Ralph Waldo Emerson"},
    {"quote":"The eye sees only what the mind is prepared to comprehend","author":"Henri Bergson"},
    {"quote":"Thus, we never see the true state of our condition till it is illustrated to us by its contraries, nor know how to value what we enjoy, but by the want of it.","author":"Daniel Defoe"},
    {"quote":"It is a modern tragedy that despair has so many spokesmen, and hope so few.","author":"Oscar Hammerstein II"},
    {"quote":"I wouldn't have seen it if I hadn't believed it.","author":"Marshall McLuhan"},
    {"quote":"Arguing that you don't care about the right to privacy because you have nothing to hide, is no different than saying you don't care about free speech because you have nothing to say.","author":"Edward Snowden"},
    {"quote":"I would rather be without a state than without a voice.","author":"Edward Snowden"},
    {"quote":"A truth that's told with bad intent beats all the lies you can invent.","author":"William Blake"},
    {"quote":"All truth passes through three stages. First, it is ridiculed. Second, it is violently opposed. Third, it is accepted as being self-evident.","author":"Arthur Schopenhauer"},
    {"quote":"I believe that unarmed truth and unconditional love will have the final word in reality. This is why right, temporarily defeated, is stronger than evil triumphant.","author":"Martin Luther King, Jr."},
    {"quote":"If the doors of perception were cleansed everything would appear to man as it is, infinite.","author":"William Blake"},
    {"quote":"When I tell the truth, it is not for the sake of convincing those who do not know it, but for the sake of defending those that do.","author":"William Blake"},
    {"quote":"I was angry with my friend: I told my wrath, my wrath did end. I was angry with my foe: I told it not, my wrath did grow.","author":"William Blake"},
    {"quote":"Keep me away from the wisdom which does not cry, the philosophy which does not laugh and the greatness which does not bow before children.","author":"Khalil Gibran"},
    {"quote":"By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.","author":"Confucius"},
    {"quote":"The only true wisdom is in knowing you know nothing.","author":"Socrates"},
    {"quote":"Reality is merely an illusion, albeit a very persistent one.","author":"Albert Einstein"},
    {"quote":"If you talk to a man in a language he understands, that goes to his head. If you talk to him in his language, that goes to his heart.","author":"Nelson Mandela"},
    {"quote":"The lust for comfort, that stealthy thing that enters the house a guest, and then becomes a host, and then a master.","author":"Khalil Gibran"},
    {"quote":"Nobody cares how much you know, until they know how much you care.","author":"Theodore Roosevelt"},
    {"quote":"Confidence is not, 'They will like me'. Confidence instead is, 'I'll be fine if they don't'.","author":"Christina Grimmie"},
    {"quote":"People aren't born strong. People grow stronger little by little, encountering difficult situations, learning not to run from them.","author":"Christina Grimmie"},
    {"quote":"We are drowning in information, while starving for wisdom. The world henceforth will be run by synthesizers, people able to put together the right information at the right time, think critically about it, and make important choices wisely.","author":"E. O. Wilson"},
    {"quote":"Freedom is never voluntarily given by the opressor; it must be demanded by the opressed.","author":"Martin Luther King Jr."}
]
